### ISSUE TITLE
Timeline for code release

### ISSUE THREAD

**Issue by mrtpk** [FER-LMC/S2D#1]
Hi,
Can you share the timeline for the code release? Looking forward to it.
Thanks for sharing your work.

**Comment by cyinen** [comment]
Thank you for your kind words and for expressing interest in our work!

We're committed to contributing to the community by sharing our code. The plan is to release the codebase upon the acceptance of our paper. We believe this timing will ensure that we provide a version of the code that is in line with the peer-reviewed research, complete with any potential revisions that may enhance the utility and clarity of the code.

We understand the anticipation and are just as eager to share our results with you. Should you wish to be notified immediately upon release, feel free to follow our repository or stay connected with updates we may post regarding our paper's status.

Your patience and support are greatly appreciated. Please, don't hesitate to reach out if you have any more questions.

Warm regards
