### ISSUE TITLE
about results on DFEW

### ISSUE THREAD

**Issue by katerynaCh** [FER-LMC/S2D#2]
Hi! Thank you for your amazing work. I just wanted to confirm that results you report on DFEW are on 1st fold rather than avg over 5 folds, in all the tables in the paper?
Thanks in advance!

**Comment by cyinen** [comment]
Thank you for your interest in our work and for reaching out with your question.

In our ablation study, we reported the results from the 1st fold of the DFEW dataset for the sake of simplicity. 

However, for the final results, we wanted to ensure a robust evaluation of our model. Therefore, we reported the average results over all 5 folds.
